### ISSUE TITLE
Errors on Ubuntu 24.04 - GLIBC_2.39 not supported

### ISSUE THREAD

**Issue by JackismyShephard** [zackees/static-sox#1]
I am getting this error on Ubuntu 24.04:

```/home/jackismyshephard/ultimate-rvc/uv/.venv/lib/python3.12/site-packages/static_sox/bin/sox-14.4.2-linux/libm.so.6: version `GLIBC_2.38' not found (required by /home/jackismyshephard/ultimate-rvc/uv/.venv/bin/python3)```

I have no problem with the binary on 22.04 though. Ubuntu 24.04 comes with GLIBC_2.39 by default while Ubuntu 22.04 comes with GLIBC_2.34 by default (at least on my machines).  Hence, I imagine the problem is that the static sox binary is compiled against GLIBC_2.38 and hence not compatible with GLIBC_2.39. Could you make a new version that is compiled against GLIBC_2.39?

**Comment by zackees** [comment]
I didn't compile these static sox binaries, I pulled them off of an ubuntu install. Can you install glibc 2.38? I'd rather not mess with this project. usually compiling against an older version of glibc is a good thing, as it's forward compatible with newer versions so I'm not too hot about swapping in a new binary that may break older toolchains.

**Comment by JackismyShephard** [comment]
@zackees Sorry for not getting back before now. The issue is actually caused by the `multiprocessing` package. I was able to solve the issue myself by removing the path to `libm.so.6` from the `LD_PRELOAD` variable before using any definitions from the `multiprocessing` package. I think it might be nice to add a `remove_paths` function (the inverse of `add_paths`) for situations like this.

**Comment by zackees** [comment]
Not sure what you mean, can you clarify?

**Comment by JackismyShephard** [comment]
@zackees Apologies for not getting back to you before. I have pushed a PR with suggested changes and also a fix for the weak parameter for the `add_paths` function
